// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	main: {
		tab: {
			/**
			 * Add a game
			 */
			add: string
		}
		head: {
			/**
			 * Enable sound
			 */
			'toggle-audio-on': string
			/**
			 * Mute
			 */
			'toggle-audio-off': string
			/**
			 * Open a new window
			 */
			'new-window': string
		}
		prompt: {
			'tabs-overflow': {
				/**
				 * Lindo doesn't support more than 6 tab per window, above that it can be laggy and buggy. But you can open a new window and it will be working just fine.
				 */
				text: string
			}
		}
	}
	notifications: {
		/**
		 * Starting turn for {{character}}
		 */
		'fight-turn': string
		/**
		 * Incoming message from {{character}}
		 */
		'private-message': string
		/**
		 * A tax collector is being attacked !
		 */
		'tax-collector': string
		/**
		 * A Kolizeum has been found !
		 */
		kolizeum: string
		/**
		 * You are invited to join {{character}}'s group.
		 */
		'party-invitation': string
		/**
		 * You have been aggressed !
		 */
		aggression: string
		/**
		 * Bank
		 */
		'sale-message': string
	}
	window: {
		changelog: {
			/**
			 * Release notes
			 */
			title: string
			/**
			 * Release
			 */
			prefixe: string
		}
		'master-password': {
			/**
			 * Continue
			 */
			'continue': string
			/**
			 * Skip this step
			 */
			skip: string
			/**
			 * Enter the master password
			 */
			'password-label': string
			/**
			 * The password is incorrect
			 */
			'password-bad': string
		}
		'update-dofus': {
			/**
			 * Lindo update
			 */
			title: string
			/**
			 * Preparing update..
			 */
			step0: string
			/**
			 * Step 1 : Downloading Dofus files
			 */
			step1: string
			/**
			 * Step 2 : Lindo patch download
			 */
			step2: string
			/**
			 * Step 3 : Version resolution
			 */
			step3: string
			/**
			 * Step 4 : Applying the patches
			 */
			step4: string
			/**
			 * Step 5 : Writing modified files
			 */
			step5: string
			/**
			 * Step 6 : Delete old files
			 */
			step6: string
			/**
			 * Step 7 : Finalization
			 */
			step7: string
			/**
			 * Step 8 : Launch of Lindo..
			 */
			step8: string
			information: {
				/**
				 * Looking for updates...
				 */
				search: string
				/**
				 * Can't download the update ! Please try again later
				 */
				error: string
				/**
				 * Try again
				 */
				retry: string
			}
		}
		options: {
			/**
			 * Options
			 */
			title: string
			button: {
				/**
				 * Completed
				 */
				close: string
			}
			general: {
				/**
				 * Re-download game data
				 */
				'reset-game': string
				/**
				 * Reset
				 */
				'reset-all': string
				/**
				 * Configure
				 */
				shortcuts: string
				/**
				 * Clear cache
				 */
				'clear-cache': string
				resolution: {
					/**
					 * Does the current resolution suit you?<br/>Automatic reset within 10 seconds..
					 */
					'confirm-body': string
				}
			}
		}
		shortcuts: {
			/**
			 * Shortcuts
			 */
			title: string
			/**
			 * You can use special keys CTRL, SHIFT, SPACE, ALT (CTRL = cmd on Mac OS X)
			 */
			description1: string
			/**
			 * You can specify your shortcut by pressing the desired keys at the same time after selecting the input
			 */
			description2: string
			tab: {
				/**
				 * Application
				 */
				application: string
				/**
				 * Interface
				 */
				'interface': string
				/**
				 * Spells
				 */
				spell: string
				/**
				 * Inventory
				 */
				inventory: string
				/**
				 * Various
				 */
				other: string
				/**
				 * Mods
				 */
				mod: string
			}
		}
		'bug-report': {
			/**
			 * Report a bug
			 */
			title: string
			/**
			 * If you've observed an unexpected behavior on Lindo, you can report it by describing it below.
			 */
			description: string
			/**
			 * Please provide at least these information:
			 */
			instructions: string
			list: {
				/**
				 * The unexpected behavior description
				 */
				'1': string
				/**
				 * How to reproduce it
				 */
				'2': string
				/**
				 * What would the usual expected behavior be
				 */
				'3': string
			}
			/**
			 * Description
			 */
			placeholder: string
			/**
			 * Send
			 */
			send: string
		}
	}
	option: {
		vip: {
			'auto-group': {
				/**
				 * Group
				 */
				header: string
				/**
				 * Enable automatic grouping
				 */
				active: string
				/**
				 * Beware, following the group leader can be considered as boting for other players, use it with caution and in unpopulated areas.
				 */
				warning: string
				/**
				 * Beware, This feature can be considered as boting for other players, use it with caution and in unpopulated areas.
				 */
				warningtimer: string
				/**
				 * The characters in the group must be friends with the leader so that the invitation is automatic.
				 */
				'explanation-1': string
				/**
				 * The members follow the leader if the latter is on the same map.
				 */
				'explanation-2': string
				/**
				 * Name of leader
				 */
				leader: string
				/**
				 * Names of characters
				 */
				members: string
				/**
				 * Add a character
				 */
				'members-add': string
				/**
				 * Follow the group leader
				 */
				'follow-leader': string
				/**
				 * Disable the Timer for the auto group
				 */
				'disable-timer': string
				/**
				 * Skip "ready" automatically
				 */
				ready: string
				/**
				 * Enter combat automatically
				 */
				fight: string
				/**
				 * Time to follow (in seconds)
				 */
				delay: string
				/**
				 * Follow the leader on a map
				 */
				'follow-on-map': string
				/**
				 * Move on the same cell the leader moves
				 */
				'strict-move': string
				/**
				 * You can't join a PvP fight automatically
				 */
				'pvp-warning': string
			}
			'multi-account': {
				/**
				 * To use this feature, a password must be configured. It will be used to start Lindo with multi-account automation.
				 */
				'home-no-master': string
				/**
				 * Multi accounts
				 */
				header: string
				/**
				 * Enable multi accounts
				 */
				active: string
				/**
				 * Window
				 */
				window: string
				/**
				 * Delete
				 */
				'delete-window': string
				/**
				 * Add a window
				 */
				'add-window': string
				/**
				 * Add an account
				 */
				add: string
				/**
				 * Username
				 */
				'account-name': string
				/**
				 * Password
				 */
				password: string
				/**
				 * Change the password
				 */
				modify_password: string
				/**
				 * Setting password
				 */
				configure_password: string
				/**
				 * Removing the password
				 */
				delete_password: string
				'request-master-password': {
					/**
					 * To access your account management, you must first enter your master password. This password was set on the first activation of the multi-account.
					 */
					explanation: string
					/**
					 * Enter your password
					 */
					label: string
					/**
					 * The password is incorrect
					 */
					bad: string
					/**
					 * Carry on
					 */
					confirm: string
					/**
					 * Skip this step
					 */
					'ignore-step': string
				}
				prompt: {
					'add-master': {
						/**
						 * Setting the Password
						 */
						title: string
						/**
						 * Save
						 */
						confirm: string
						/**
						 * Cancel
						 */
						cancel: string
						/**
						 * The password must contain at least {{lenght}} characters
						 */
						'min-lenght': string
						/**
						 * The password will now be used to start the application.
						 */
						'success-text': string
					}
					'edit-master': {
						/**
						 * Changing the password
						 */
						title: string
						/**
						 * Old password
						 */
						'input-old-placeholder': string
						/**
						 * New password
						 */
						'input-new-placeholder': string
						/**
						 * Save
						 */
						confirm: string
						/**
						 * Cancel
						 */
						cancel: string
						/**
						 * The new password must contain at least {{lenght}} characters
						 */
						'min-lenght': string
						/**
						 * The old password is incorrect
						 */
						'incorrect-old': string
						/**
						 * The password has been changed.
						 */
						'success-text': string
					}
					'delete-master': {
						/**
						 * Removing the password
						 */
						title: string
						/**
						 * Are you sure?<br/>This will delete the saved accounts.
						 */
						text: string
						/**
						 * Remove
						 */
						confirm: string
						/**
						 * Cancel
						 */
						cancel: string
						/**
						 * The password has been deleted.
						 */
						'success-text': string
					}
					'maximum-account': {
						/**
						 * Oops!
						 */
						title: string
						/**
						 * You can not save more than 4 accounts without Wabbit donor rank.
						 */
						text: string
						/**
						 * Increase my VIP rank
						 */
						confirm: string
						/**
						 * I understood
						 */
						cancel: string
					}
					'add-account': {
						/**
						 * Adding an account
						 */
						title: string
						/**
						 * Username
						 */
						'input-login-placeholder': string
						/**
						 * Password
						 */
						'input-password-placeholder': string
						/**
						 * Save
						 */
						confirm: string
						/**
						 * Cancel
						 */
						cancel: string
						/**
						 * The username must contain at least 1 character
						 */
						'min-lenght-login': string
						/**
						 * The password must contain at least 1 character
						 */
						'min-lenght-password': string
					}
					'edit-account': {
						/**
						 * Changing an account
						 */
						title: string
						/**
						 * Username
						 */
						'input-login-placeholder': string
						/**
						 * Password
						 */
						'input-password-placeholder': string
						/**
						 * Save
						 */
						confirm: string
						/**
						 * Cancel
						 */
						cancel: string
						/**
						 * The username must contain at least 1 character
						 */
						'min-lenght-login': string
						/**
						 * The password must contain at least 1 character
						 */
						'min-lenght-password': string
					}
				}
			}
			zaapsearchfilter: {
				/**
				 * Search a zaap
				 */
				placeholder: string
				/**
				 * Search a zaapi
				 */
				placeholderZaapi: string
				/**
				 * Search a prisme
				 */
				placeholderPrisme: string
			}
			'party-info': {
				/**
				 * Show party's level
				 */
				'header-lvl': string
				/**
				 * Show party's prospecting
				 */
				'header-pp': string
				/**
				 * Lvl.
				 */
				level: string
			}
			jobsxp: {
				/**
				 *  XP missing<br>before level 
				 */
				text: string
			}
			monstertooltip: {
				/**
				 * Level
				 */
				level: string
				/**
				 * Group
				 */
				group: string
			}
		}
		general: {
			/**
			 * General
			 */
			title: string
			/**
			 * Interface
			 */
			'interface': string
			/**
			 * Sound
			 */
			sound: string
			/**
			 * Keyboard shortcuts
			 */
			shortcuts: string
			/**
			 * Game data
			 */
			'game-data': string
			/**
			 * Language
			 */
			language: string
			/**
			 * Resolution
			 */
			resolution: string
			/**
			 * Hide the Shop button
			 */
			'hide-shop': string
			/**
			 * Full screen
			 */
			'full-screen': string
			/**
			 * Hide the multi-account tab bar
			 */
			'hide-tab': string
			/**
			 * Automatically switch to an account when its turn starts
			 */
			'focus-fight-turn': string
			/**
			 * Enable local map download (beta)
			 */
			'local-content': string
			/**
			 * Game sound only on foreground window
			 */
			'sound-focus': string
			/**
			 * Play on Dofus Touch Early
			 */
			early: string
			/**
			 * Apply and restart
			 */
			restart: string
		}
		shortcuts: {
			/**
			 * Shortcuts
			 */
			title: string
			diver: {
				/**
				 * Miscellaneous
				 */
				header: string
				/**
				 * End your turn / Ready (fight)
				 */
				'end-turn': string
				/**
				 * Open the chat
				 */
				'open-chat': string
				/**
				 * Open menu when no window is open (ECHAP)
				 */
				'active-open-menu': string
				/**
				 * Open the menu
				 */
				'open-menu': string
				/**
				 * Go to Upper Map
				 */
				go_up: string
				/**
				 * Go to Lower Map
				 */
				go_bottom: string
				/**
				 * Go to Left Map
				 */
				go_left: string
				/**
				 * Go to Right Map
				 */
				go_right: string
			}
			interfaces: {
				/**
				 * Interfaces
				 */
				header: string
				/**
				 * Character
				 */
				carac: string
				/**
				 * Spells
				 */
				spell: string
				/**
				 * Inventory
				 */
				bag: string
				/**
				 * Market place
				 */
				bidhouse: string
				/**
				 * Map
				 */
				map: string
				/**
				 * Friends
				 */
				friend: string
				/**
				 * Quests
				 */
				book: string
				/**
				 * Guild
				 */
				guild: string
				/**
				 * Kolizeum
				 */
				conquest: string
				/**
				 * Shop
				 */
				goultine: string
				/**
				 * Jobs
				 */
				job: string
				/**
				 * Alliance
				 */
				alliance: string
				/**
				 * Mount
				 */
				mount: string
				/**
				 * List of Guilds and Alliances
				 */
				directory: string
				/**
				 * Alignment
				 */
				alignement: string
				/**
				 * Bestiary
				 */
				bestiary: string
				/**
				 * Titles and Ornaments
				 */
				title: string
				/**
				 * Achievements
				 */
				achievement: string
				/**
				 * Daily Quests
				 */
				dailyQuest: string
				/**
				 * Spouse
				 */
				spouse: string
				/**
				 * Shopkeeper
				 */
				shop: string
			}
			items: {
				/**
				 * Items
				 */
				header: string
				/**
				 * Slot {{x}}
				 */
				slot: string
			}
			'no-emu': {
				/**
				 * Lindo
				 */
				header: string
				/**
				 * New window
				 */
				'new-window': string
				/**
				 * New tab
				 */
				'new-tab': string
				/**
				 * Tab {{x}}
				 */
				tab: string
				/**
				 * Next tab
				 */
				'next-tab': string
				/**
				 * Previous tab
				 */
				'prev-tab': string
			}
			spells: {
				/**
				 * Spells
				 */
				header: string
				/**
				 * Slot {{x}}
				 */
				slot: string
			}
			mods: {
				/**
				 * Show/hide map resources
				 */
				'show-resources': string
				/**
				 * Show/hide life bars
				 */
				'health-bar': string
				/**
				 * Show/hide monsters tooltip
				 */
				'monster-tooltip': string
			}
		}
		features: {
			/**
			 * Features
			 */
			title: string
			general: {
				menu: {
					/**
					 * General
					 */
					general: string
					/**
					 * Fight
					 */
					fight: string
					/**
					 * Group
					 */
					group: string
					/**
					 * Job
					 */
					job: string
				}
				/**
				 * General
				 */
				header: string
				/**
				 * Extend the delay before disconnection for inactivity
				 */
				'disable-inactivity': string
				/**
				 * Activate the display of the life bars below the fighters
				 */
				'health-bar': string
				/**
				 * Activate the display of the job xp need for leveling
				 */
				jobsxp: string
				/**
				 * Estimating spell damage in battle
				 */
				estimator: string
				/**
				 * Show combats chronometer
				 */
				fightchronometer: string
				/**
				 * Show zaap search filter
				 */
				zaapsearchfilter: string
				/**
				 * Show map resources
				 */
				'show-resources': string
				/**
				 * Activate the display of the remaining time below the ressources
				 */
				'harvest-indicator': string
				/**
				 * Add an indicator to know if the members of a group are on the same map
				 */
				'party-member-on-map': string
				/**
				 * Display monsters groups informations on the map
				 */
				'monster-tooltip': string
				/**
				 * Shortcut for show/hide monsters tooltip
				 */
				'monster-tooltip-shortcut': string
				/**
				 * Show fighters timeline vertically
				 */
				'vertical-timeline': string
				/**
				 * Show challenge XP/Drop bonus
				 */
				'chall-percent': string
			}
			groups: {
				/**
				 * Groups
				 */
				header: string
			}
			accounts: {
				/**
				 * Accounts
				 */
				header: string
			}
		}
		notifications: {
			/**
			 * Notifications
			 */
			title: string
			/**
			 * You can receive notifications from the game when the application is on the background. You will be notified:
			 */
			description: string
			/**
			 * When your turn starts (fight)
			 */
			'fight-turn': string
			/**
			 * By incoming private messages
			 */
			'private-message': string
			/**
			 * When a tax collector is attacked
			 */
			'tax-collector': string
			/**
			 * When a kolizeum fight is found
			 */
			kolizeum: string
			/**
			 * When someone invites you to join a group
			 */
			'party-invitation': string
			/**
			 * When someone aggresses you
			 */
			aggression: string
			/**
			 * When an item is sold
			 */
			'sale-message': string
		}
		about: {
			/**
			 * About
			 */
			title: string
			links: {
				/**
				 * Website
				 */
				website: string
				/**
				 * Release notes
				 */
				changelog: string
			}
			/**
			 * Lindo is an open-source software that allows you to play DOFUS Touch from your computer.
			 */
			text0: string
			/**
			 * Unlike an Android emulator, the code is directly interpreted by your computer, which makes it faster so you can play DOFUS Touch with the full performance of your computer !
			 */
			text1: string
			/**
			 * Originally known as DOFUS Touch No-Emu, this software developed by Daniel and Thomas was forced to close cause of an avertissement from Ankama.
			 */
			text2: string
		}
		/**
		 * Reset
		 */
		reset: string
		/**
		 * Apply
		 */
		save: string
		prompt: {
			'reset-option': {
				/**
				 * By continuing, all parameters will be reset.<br/>This operation is not reversible.
				 */
				text: string
			}
		}
	}
	prompt: {
		title: {
			/**
			 * Confirmation required
			 */
			confirm: string
			/**
			 * Warning !
			 */
			warning: string
			/**
			 * Successful operation !
			 */
			success: string
			/**
			 * Operation failed !
			 */
			error: string
			/**
			 * Information
			 */
			info: string
		}
		button: {
			/**
			 * Cancel
			 */
			cancel: string
			/**
			 * I confirm
			 */
			confirm: string
			/**
			 * Close
			 */
			close: string
		}
	}
}

export type TranslationFunctions = {
	main: {
		tab: {
			/**
			 * Add a game
			 */
			add: () => LocalizedString
		}
		head: {
			/**
			 * Enable sound
			 */
			'toggle-audio-on': () => LocalizedString
			/**
			 * Mute
			 */
			'toggle-audio-off': () => LocalizedString
			/**
			 * Open a new window
			 */
			'new-window': () => LocalizedString
		}
		prompt: {
			'tabs-overflow': {
				/**
				 * Lindo doesn't support more than 6 tab per window, above that it can be laggy and buggy. But you can open a new window and it will be working just fine.
				 */
				text: () => LocalizedString
			}
		}
	}
	notifications: {
		/**
		 * Starting turn for {{character}}
		 */
		'fight-turn': (arg0: string | number | boolean) => LocalizedString
		/**
		 * Incoming message from {{character}}
		 */
		'private-message': (arg0: string | number | boolean) => LocalizedString
		/**
		 * A tax collector is being attacked !
		 */
		'tax-collector': () => LocalizedString
		/**
		 * A Kolizeum has been found !
		 */
		kolizeum: () => LocalizedString
		/**
		 * You are invited to join {{character}}'s group.
		 */
		'party-invitation': (arg0: string | number | boolean) => LocalizedString
		/**
		 * You have been aggressed !
		 */
		aggression: () => LocalizedString
		/**
		 * Bank
		 */
		'sale-message': () => LocalizedString
	}
	window: {
		changelog: {
			/**
			 * Release notes
			 */
			title: () => LocalizedString
			/**
			 * Release
			 */
			prefixe: () => LocalizedString
		}
		'master-password': {
			/**
			 * Continue
			 */
			'continue': () => LocalizedString
			/**
			 * Skip this step
			 */
			skip: () => LocalizedString
			/**
			 * Enter the master password
			 */
			'password-label': () => LocalizedString
			/**
			 * The password is incorrect
			 */
			'password-bad': () => LocalizedString
		}
		'update-dofus': {
			/**
			 * Lindo update
			 */
			title: () => LocalizedString
			/**
			 * Preparing update..
			 */
			step0: () => LocalizedString
			/**
			 * Step 1 : Downloading Dofus files
			 */
			step1: () => LocalizedString
			/**
			 * Step 2 : Lindo patch download
			 */
			step2: () => LocalizedString
			/**
			 * Step 3 : Version resolution
			 */
			step3: () => LocalizedString
			/**
			 * Step 4 : Applying the patches
			 */
			step4: () => LocalizedString
			/**
			 * Step 5 : Writing modified files
			 */
			step5: () => LocalizedString
			/**
			 * Step 6 : Delete old files
			 */
			step6: () => LocalizedString
			/**
			 * Step 7 : Finalization
			 */
			step7: () => LocalizedString
			/**
			 * Step 8 : Launch of Lindo..
			 */
			step8: () => LocalizedString
			information: {
				/**
				 * Looking for updates...
				 */
				search: () => LocalizedString
				/**
				 * Can't download the update ! Please try again later
				 */
				error: () => LocalizedString
				/**
				 * Try again
				 */
				retry: () => LocalizedString
			}
		}
		options: {
			/**
			 * Options
			 */
			title: () => LocalizedString
			button: {
				/**
				 * Completed
				 */
				close: () => LocalizedString
			}
			general: {
				/**
				 * Re-download game data
				 */
				'reset-game': () => LocalizedString
				/**
				 * Reset
				 */
				'reset-all': () => LocalizedString
				/**
				 * Configure
				 */
				shortcuts: () => LocalizedString
				/**
				 * Clear cache
				 */
				'clear-cache': () => LocalizedString
				resolution: {
					/**
					 * Does the current resolution suit you?<br/>Automatic reset within 10 seconds..
					 */
					'confirm-body': () => LocalizedString
				}
			}
		}
		shortcuts: {
			/**
			 * Shortcuts
			 */
			title: () => LocalizedString
			/**
			 * You can use special keys CTRL, SHIFT, SPACE, ALT (CTRL = cmd on Mac OS X)
			 */
			description1: () => LocalizedString
			/**
			 * You can specify your shortcut by pressing the desired keys at the same time after selecting the input
			 */
			description2: () => LocalizedString
			tab: {
				/**
				 * Application
				 */
				application: () => LocalizedString
				/**
				 * Interface
				 */
				'interface': () => LocalizedString
				/**
				 * Spells
				 */
				spell: () => LocalizedString
				/**
				 * Inventory
				 */
				inventory: () => LocalizedString
				/**
				 * Various
				 */
				other: () => LocalizedString
				/**
				 * Mods
				 */
				mod: () => LocalizedString
			}
		}
		'bug-report': {
			/**
			 * Report a bug
			 */
			title: () => LocalizedString
			/**
			 * If you've observed an unexpected behavior on Lindo, you can report it by describing it below.
			 */
			description: () => LocalizedString
			/**
			 * Please provide at least these information:
			 */
			instructions: () => LocalizedString
			list: {
				/**
				 * The unexpected behavior description
				 */
				'1': () => LocalizedString
				/**
				 * How to reproduce it
				 */
				'2': () => LocalizedString
				/**
				 * What would the usual expected behavior be
				 */
				'3': () => LocalizedString
			}
			/**
			 * Description
			 */
			placeholder: () => LocalizedString
			/**
			 * Send
			 */
			send: () => LocalizedString
		}
	}
	option: {
		vip: {
			'auto-group': {
				/**
				 * Group
				 */
				header: () => LocalizedString
				/**
				 * Enable automatic grouping
				 */
				active: () => LocalizedString
				/**
				 * Beware, following the group leader can be considered as boting for other players, use it with caution and in unpopulated areas.
				 */
				warning: () => LocalizedString
				/**
				 * Beware, This feature can be considered as boting for other players, use it with caution and in unpopulated areas.
				 */
				warningtimer: () => LocalizedString
				/**
				 * The characters in the group must be friends with the leader so that the invitation is automatic.
				 */
				'explanation-1': () => LocalizedString
				/**
				 * The members follow the leader if the latter is on the same map.
				 */
				'explanation-2': () => LocalizedString
				/**
				 * Name of leader
				 */
				leader: () => LocalizedString
				/**
				 * Names of characters
				 */
				members: () => LocalizedString
				/**
				 * Add a character
				 */
				'members-add': () => LocalizedString
				/**
				 * Follow the group leader
				 */
				'follow-leader': () => LocalizedString
				/**
				 * Disable the Timer for the auto group
				 */
				'disable-timer': () => LocalizedString
				/**
				 * Skip "ready" automatically
				 */
				ready: () => LocalizedString
				/**
				 * Enter combat automatically
				 */
				fight: () => LocalizedString
				/**
				 * Time to follow (in seconds)
				 */
				delay: () => LocalizedString
				/**
				 * Follow the leader on a map
				 */
				'follow-on-map': () => LocalizedString
				/**
				 * Move on the same cell the leader moves
				 */
				'strict-move': () => LocalizedString
				/**
				 * You can't join a PvP fight automatically
				 */
				'pvp-warning': () => LocalizedString
			}
			'multi-account': {
				/**
				 * To use this feature, a password must be configured. It will be used to start Lindo with multi-account automation.
				 */
				'home-no-master': () => LocalizedString
				/**
				 * Multi accounts
				 */
				header: () => LocalizedString
				/**
				 * Enable multi accounts
				 */
				active: () => LocalizedString
				/**
				 * Window
				 */
				window: () => LocalizedString
				/**
				 * Delete
				 */
				'delete-window': () => LocalizedString
				/**
				 * Add a window
				 */
				'add-window': () => LocalizedString
				/**
				 * Add an account
				 */
				add: () => LocalizedString
				/**
				 * Username
				 */
				'account-name': () => LocalizedString
				/**
				 * Password
				 */
				password: () => LocalizedString
				/**
				 * Change the password
				 */
				modify_password: () => LocalizedString
				/**
				 * Setting password
				 */
				configure_password: () => LocalizedString
				/**
				 * Removing the password
				 */
				delete_password: () => LocalizedString
				'request-master-password': {
					/**
					 * To access your account management, you must first enter your master password. This password was set on the first activation of the multi-account.
					 */
					explanation: () => LocalizedString
					/**
					 * Enter your password
					 */
					label: () => LocalizedString
					/**
					 * The password is incorrect
					 */
					bad: () => LocalizedString
					/**
					 * Carry on
					 */
					confirm: () => LocalizedString
					/**
					 * Skip this step
					 */
					'ignore-step': () => LocalizedString
				}
				prompt: {
					'add-master': {
						/**
						 * Setting the Password
						 */
						title: () => LocalizedString
						/**
						 * Save
						 */
						confirm: () => LocalizedString
						/**
						 * Cancel
						 */
						cancel: () => LocalizedString
						/**
						 * The password must contain at least {{lenght}} characters
						 */
						'min-lenght': (arg0: string | number | boolean) => LocalizedString
						/**
						 * The password will now be used to start the application.
						 */
						'success-text': () => LocalizedString
					}
					'edit-master': {
						/**
						 * Changing the password
						 */
						title: () => LocalizedString
						/**
						 * Old password
						 */
						'input-old-placeholder': () => LocalizedString
						/**
						 * New password
						 */
						'input-new-placeholder': () => LocalizedString
						/**
						 * Save
						 */
						confirm: () => LocalizedString
						/**
						 * Cancel
						 */
						cancel: () => LocalizedString
						/**
						 * The new password must contain at least {{lenght}} characters
						 */
						'min-lenght': (arg0: string | number | boolean) => LocalizedString
						/**
						 * The old password is incorrect
						 */
						'incorrect-old': () => LocalizedString
						/**
						 * The password has been changed.
						 */
						'success-text': () => LocalizedString
					}
					'delete-master': {
						/**
						 * Removing the password
						 */
						title: () => LocalizedString
						/**
						 * Are you sure?<br/>This will delete the saved accounts.
						 */
						text: () => LocalizedString
						/**
						 * Remove
						 */
						confirm: () => LocalizedString
						/**
						 * Cancel
						 */
						cancel: () => LocalizedString
						/**
						 * The password has been deleted.
						 */
						'success-text': () => LocalizedString
					}
					'maximum-account': {
						/**
						 * Oops!
						 */
						title: () => LocalizedString
						/**
						 * You can not save more than 4 accounts without Wabbit donor rank.
						 */
						text: () => LocalizedString
						/**
						 * Increase my VIP rank
						 */
						confirm: () => LocalizedString
						/**
						 * I understood
						 */
						cancel: () => LocalizedString
					}
					'add-account': {
						/**
						 * Adding an account
						 */
						title: () => LocalizedString
						/**
						 * Username
						 */
						'input-login-placeholder': () => LocalizedString
						/**
						 * Password
						 */
						'input-password-placeholder': () => LocalizedString
						/**
						 * Save
						 */
						confirm: () => LocalizedString
						/**
						 * Cancel
						 */
						cancel: () => LocalizedString
						/**
						 * The username must contain at least 1 character
						 */
						'min-lenght-login': () => LocalizedString
						/**
						 * The password must contain at least 1 character
						 */
						'min-lenght-password': () => LocalizedString
					}
					'edit-account': {
						/**
						 * Changing an account
						 */
						title: () => LocalizedString
						/**
						 * Username
						 */
						'input-login-placeholder': () => LocalizedString
						/**
						 * Password
						 */
						'input-password-placeholder': () => LocalizedString
						/**
						 * Save
						 */
						confirm: () => LocalizedString
						/**
						 * Cancel
						 */
						cancel: () => LocalizedString
						/**
						 * The username must contain at least 1 character
						 */
						'min-lenght-login': () => LocalizedString
						/**
						 * The password must contain at least 1 character
						 */
						'min-lenght-password': () => LocalizedString
					}
				}
			}
			zaapsearchfilter: {
				/**
				 * Search a zaap
				 */
				placeholder: () => LocalizedString
				/**
				 * Search a zaapi
				 */
				placeholderZaapi: () => LocalizedString
				/**
				 * Search a prisme
				 */
				placeholderPrisme: () => LocalizedString
			}
			'party-info': {
				/**
				 * Show party's level
				 */
				'header-lvl': () => LocalizedString
				/**
				 * Show party's prospecting
				 */
				'header-pp': () => LocalizedString
				/**
				 * Lvl.
				 */
				level: () => LocalizedString
			}
			jobsxp: {
				/**
				 *  XP missing<br>before level 
				 */
				text: () => LocalizedString
			}
			monstertooltip: {
				/**
				 * Level
				 */
				level: () => LocalizedString
				/**
				 * Group
				 */
				group: () => LocalizedString
			}
		}
		general: {
			/**
			 * General
			 */
			title: () => LocalizedString
			/**
			 * Interface
			 */
			'interface': () => LocalizedString
			/**
			 * Sound
			 */
			sound: () => LocalizedString
			/**
			 * Keyboard shortcuts
			 */
			shortcuts: () => LocalizedString
			/**
			 * Game data
			 */
			'game-data': () => LocalizedString
			/**
			 * Language
			 */
			language: () => LocalizedString
			/**
			 * Resolution
			 */
			resolution: () => LocalizedString
			/**
			 * Hide the Shop button
			 */
			'hide-shop': () => LocalizedString
			/**
			 * Full screen
			 */
			'full-screen': () => LocalizedString
			/**
			 * Hide the multi-account tab bar
			 */
			'hide-tab': () => LocalizedString
			/**
			 * Automatically switch to an account when its turn starts
			 */
			'focus-fight-turn': () => LocalizedString
			/**
			 * Enable local map download (beta)
			 */
			'local-content': () => LocalizedString
			/**
			 * Game sound only on foreground window
			 */
			'sound-focus': () => LocalizedString
			/**
			 * Play on Dofus Touch Early
			 */
			early: () => LocalizedString
			/**
			 * Apply and restart
			 */
			restart: () => LocalizedString
		}
		shortcuts: {
			/**
			 * Shortcuts
			 */
			title: () => LocalizedString
			diver: {
				/**
				 * Miscellaneous
				 */
				header: () => LocalizedString
				/**
				 * End your turn / Ready (fight)
				 */
				'end-turn': () => LocalizedString
				/**
				 * Open the chat
				 */
				'open-chat': () => LocalizedString
				/**
				 * Open menu when no window is open (ECHAP)
				 */
				'active-open-menu': () => LocalizedString
				/**
				 * Open the menu
				 */
				'open-menu': () => LocalizedString
				/**
				 * Go to Upper Map
				 */
				go_up: () => LocalizedString
				/**
				 * Go to Lower Map
				 */
				go_bottom: () => LocalizedString
				/**
				 * Go to Left Map
				 */
				go_left: () => LocalizedString
				/**
				 * Go to Right Map
				 */
				go_right: () => LocalizedString
			}
			interfaces: {
				/**
				 * Interfaces
				 */
				header: () => LocalizedString
				/**
				 * Character
				 */
				carac: () => LocalizedString
				/**
				 * Spells
				 */
				spell: () => LocalizedString
				/**
				 * Inventory
				 */
				bag: () => LocalizedString
				/**
				 * Market place
				 */
				bidhouse: () => LocalizedString
				/**
				 * Map
				 */
				map: () => LocalizedString
				/**
				 * Friends
				 */
				friend: () => LocalizedString
				/**
				 * Quests
				 */
				book: () => LocalizedString
				/**
				 * Guild
				 */
				guild: () => LocalizedString
				/**
				 * Kolizeum
				 */
				conquest: () => LocalizedString
				/**
				 * Shop
				 */
				goultine: () => LocalizedString
				/**
				 * Jobs
				 */
				job: () => LocalizedString
				/**
				 * Alliance
				 */
				alliance: () => LocalizedString
				/**
				 * Mount
				 */
				mount: () => LocalizedString
				/**
				 * List of Guilds and Alliances
				 */
				directory: () => LocalizedString
				/**
				 * Alignment
				 */
				alignement: () => LocalizedString
				/**
				 * Bestiary
				 */
				bestiary: () => LocalizedString
				/**
				 * Titles and Ornaments
				 */
				title: () => LocalizedString
				/**
				 * Achievements
				 */
				achievement: () => LocalizedString
				/**
				 * Daily Quests
				 */
				dailyQuest: () => LocalizedString
				/**
				 * Spouse
				 */
				spouse: () => LocalizedString
				/**
				 * Shopkeeper
				 */
				shop: () => LocalizedString
			}
			items: {
				/**
				 * Items
				 */
				header: () => LocalizedString
				/**
				 * Slot {{x}}
				 */
				slot: (arg0: string | number | boolean) => LocalizedString
			}
			'no-emu': {
				/**
				 * Lindo
				 */
				header: () => LocalizedString
				/**
				 * New window
				 */
				'new-window': () => LocalizedString
				/**
				 * New tab
				 */
				'new-tab': () => LocalizedString
				/**
				 * Tab {{x}}
				 */
				tab: (arg0: string | number | boolean) => LocalizedString
				/**
				 * Next tab
				 */
				'next-tab': () => LocalizedString
				/**
				 * Previous tab
				 */
				'prev-tab': () => LocalizedString
			}
			spells: {
				/**
				 * Spells
				 */
				header: () => LocalizedString
				/**
				 * Slot {{x}}
				 */
				slot: (arg0: string | number | boolean) => LocalizedString
			}
			mods: {
				/**
				 * Show/hide map resources
				 */
				'show-resources': () => LocalizedString
				/**
				 * Show/hide life bars
				 */
				'health-bar': () => LocalizedString
				/**
				 * Show/hide monsters tooltip
				 */
				'monster-tooltip': () => LocalizedString
			}
		}
		features: {
			/**
			 * Features
			 */
			title: () => LocalizedString
			general: {
				menu: {
					/**
					 * General
					 */
					general: () => LocalizedString
					/**
					 * Fight
					 */
					fight: () => LocalizedString
					/**
					 * Group
					 */
					group: () => LocalizedString
					/**
					 * Job
					 */
					job: () => LocalizedString
				}
				/**
				 * General
				 */
				header: () => LocalizedString
				/**
				 * Extend the delay before disconnection for inactivity
				 */
				'disable-inactivity': () => LocalizedString
				/**
				 * Activate the display of the life bars below the fighters
				 */
				'health-bar': () => LocalizedString
				/**
				 * Activate the display of the job xp need for leveling
				 */
				jobsxp: () => LocalizedString
				/**
				 * Estimating spell damage in battle
				 */
				estimator: () => LocalizedString
				/**
				 * Show combats chronometer
				 */
				fightchronometer: () => LocalizedString
				/**
				 * Show zaap search filter
				 */
				zaapsearchfilter: () => LocalizedString
				/**
				 * Show map resources
				 */
				'show-resources': () => LocalizedString
				/**
				 * Activate the display of the remaining time below the ressources
				 */
				'harvest-indicator': () => LocalizedString
				/**
				 * Add an indicator to know if the members of a group are on the same map
				 */
				'party-member-on-map': () => LocalizedString
				/**
				 * Display monsters groups informations on the map
				 */
				'monster-tooltip': () => LocalizedString
				/**
				 * Shortcut for show/hide monsters tooltip
				 */
				'monster-tooltip-shortcut': () => LocalizedString
				/**
				 * Show fighters timeline vertically
				 */
				'vertical-timeline': () => LocalizedString
				/**
				 * Show challenge XP/Drop bonus
				 */
				'chall-percent': () => LocalizedString
			}
			groups: {
				/**
				 * Groups
				 */
				header: () => LocalizedString
			}
			accounts: {
				/**
				 * Accounts
				 */
				header: () => LocalizedString
			}
		}
		notifications: {
			/**
			 * Notifications
			 */
			title: () => LocalizedString
			/**
			 * You can receive notifications from the game when the application is on the background. You will be notified:
			 */
			description: () => LocalizedString
			/**
			 * When your turn starts (fight)
			 */
			'fight-turn': () => LocalizedString
			/**
			 * By incoming private messages
			 */
			'private-message': () => LocalizedString
			/**
			 * When a tax collector is attacked
			 */
			'tax-collector': () => LocalizedString
			/**
			 * When a kolizeum fight is found
			 */
			kolizeum: () => LocalizedString
			/**
			 * When someone invites you to join a group
			 */
			'party-invitation': () => LocalizedString
			/**
			 * When someone aggresses you
			 */
			aggression: () => LocalizedString
			/**
			 * When an item is sold
			 */
			'sale-message': () => LocalizedString
		}
		about: {
			/**
			 * About
			 */
			title: () => LocalizedString
			links: {
				/**
				 * Website
				 */
				website: () => LocalizedString
				/**
				 * Release notes
				 */
				changelog: () => LocalizedString
			}
			/**
			 * Lindo is an open-source software that allows you to play DOFUS Touch from your computer.
			 */
			text0: () => LocalizedString
			/**
			 * Unlike an Android emulator, the code is directly interpreted by your computer, which makes it faster so you can play DOFUS Touch with the full performance of your computer !
			 */
			text1: () => LocalizedString
			/**
			 * Originally known as DOFUS Touch No-Emu, this software developed by Daniel and Thomas was forced to close cause of an avertissement from Ankama.
			 */
			text2: () => LocalizedString
		}
		/**
		 * Reset
		 */
		reset: () => LocalizedString
		/**
		 * Apply
		 */
		save: () => LocalizedString
		prompt: {
			'reset-option': {
				/**
				 * By continuing, all parameters will be reset.<br/>This operation is not reversible.
				 */
				text: () => LocalizedString
			}
		}
	}
	prompt: {
		title: {
			/**
			 * Confirmation required
			 */
			confirm: () => LocalizedString
			/**
			 * Warning !
			 */
			warning: () => LocalizedString
			/**
			 * Successful operation !
			 */
			success: () => LocalizedString
			/**
			 * Operation failed !
			 */
			error: () => LocalizedString
			/**
			 * Information
			 */
			info: () => LocalizedString
		}
		button: {
			/**
			 * Cancel
			 */
			cancel: () => LocalizedString
			/**
			 * I confirm
			 */
			confirm: () => LocalizedString
			/**
			 * Close
			 */
			close: () => LocalizedString
		}
	}
}

export type Formatters = {}
